package com.zayar.tempbox;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.view.*;
import android.widget.*;
import android.webkit.*;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
    private final int PAGE=Color.rgb(242,245,251), WHITE=Color.WHITE, INK=Color.rgb(20,25,34), MUTED=Color.rgb(142,147,157), GREEN=Color.rgb(0,207,139), LINE=Color.rgb(225,229,237);
    private final ExecutorService io=Executors.newSingleThreadExecutor();
    private final Handler ui=new Handler(Looper.getMainLooper());
    private final String[] providers={"https://api.mail.tm","https://api.mail.gw"};
    private final String SMARTLINK="https://www.profitableratecpmnetwork.com/dzxg7k5c?key=5feedb79d22614b3c5a50868fa4f8884";
    private TextView email,status,count; private LinearLayout inbox; private Button copy,refresh,change;
    private String token="",provider=""; private boolean english=false;
    private final Runnable poll=new Runnable(){public void run(){loadMessages();ui.postDelayed(this,10000);}};

    @Override public void onCreate(Bundle b){super.onCreate(b);english=getSharedPreferences("settings",MODE_PRIVATE).getBoolean("english",false);buildUi();createMailbox();}
    @Override protected void onDestroy(){ui.removeCallbacks(poll);io.shutdownNow();super.onDestroy();}
    private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w,h);}
    private String tr(String my,String en){return english?en:my;}
    private GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    private GradientDrawable outlined(int color,int radius){GradientDrawable d=shape(color,radius);d.setStroke(dp(1),LINE);return d;}
    private TextView text(String value,int size,int color){TextView v=new TextView(this);v.setText(value);v.setTextSize(size);v.setTextColor(color);v.setLineSpacing(0,1.18f);return v;}

    private void buildUi(){
        getWindow().setStatusBarColor(PAGE);getWindow().setNavigationBarColor(PAGE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(PAGE);
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(24),dp(20),dp(28));scroll.addView(root);

        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);
        Button menu=new Button(this);menu.setText("≡");menu.setTextSize(21);menu.setTextColor(MUTED);menu.setBackground(shape(WHITE,24));top.addView(menu,lp(dp(52),dp(52)));
        TextView title=text("Temp Mail",21,INK);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setGravity(Gravity.CENTER);top.addView(title,new LinearLayout.LayoutParams(0,dp(52),1));
        Button lang=new Button(this);lang.setText(english?"မြန်မာ":"EN");lang.setTextSize(12);lang.setTextColor(INK);lang.setTypeface(Typeface.DEFAULT,Typeface.BOLD);lang.setBackground(shape(WHITE,24));top.addView(lang,lp(dp(58),dp(52)));root.addView(top);
        lang.setOnClickListener(v->{getSharedPreferences("settings",MODE_PRIVATE).edit().putBoolean("english",!english).apply();recreate();});
        menu.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("TempBox").setMessage(tr("အခမဲ့ ယာယီအီးမေးလ် App\nVersion 1.7.0","Free temporary email app\nVersion 1.7.0")).setNeutralButton(tr("Auto ကြော်ငြာ ပြောင်းမယ်","Toggle auto ad"),(d,w)->{boolean enabled=!getSharedPreferences("settings",MODE_PRIVATE).getBoolean("auto_smartlink",false);getSharedPreferences("settings",MODE_PRIVATE).edit().putBoolean("auto_smartlink",enabled).apply();Toast.makeText(this,enabled?tr("Auto ကြော်ငြာ ဖွင့်ထားသည်","Auto ad enabled"):tr("Auto ကြော်ငြာ ပိတ်ထားသည်","Auto ad disabled"),Toast.LENGTH_SHORT).show();}).setPositiveButton(tr("ပိတ်မယ်","Close"),null).show());

        LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER_HORIZONTAL);card.setPadding(dp(22),dp(30),dp(22),dp(24));card.setBackground(outlined(WHITE,28));LinearLayout.LayoutParams cardLp=lp(-1,-2);cardLp.setMargins(0,dp(52),0,0);root.addView(card,cardLp);
        TextView icon=text("✉",45,Color.WHITE);icon.setGravity(Gravity.CENTER);icon.setBackground(shape(GREEN,22));card.addView(icon,lp(dp(92),dp(92)));
        status=text(tr("အီးမေးလ်ဖန်တီးနေသည်…","Creating email…"),13,GREEN);status.setGravity(Gravity.CENTER);LinearLayout.LayoutParams statLp=lp(-1,-2);statLp.topMargin=dp(22);card.addView(status,statLp);
        email=text(tr("ဖန်တီးနေသည်…","Creating…"),22,INK);email.setTypeface(Typeface.DEFAULT,Typeface.BOLD);email.setGravity(Gravity.CENTER);email.setTextIsSelectable(true);LinearLayout.LayoutParams emailLp=lp(-1,-2);emailLp.setMargins(0,dp(8),0,dp(3));card.addView(email,emailLp);
        TextView caption=text(tr("သင့်ယာယီအီးမေးလ်လိပ်စာ","Your Temporary Email Address"),14,MUTED);caption.setGravity(Gravity.CENTER);card.addView(caption,lp(-1,-2));
        copy=new Button(this);copy.setText(tr("▣  Email ကူးယူမယ်","▣  Copy email"));copy.setTextSize(16);copy.setTextColor(Color.WHITE);copy.setTypeface(Typeface.DEFAULT,Typeface.BOLD);copy.setEnabled(false);copy.setBackground(shape(GREEN,15));LinearLayout.LayoutParams copyLp=lp(-1,dp(58));copyLp.topMargin=dp(34);card.addView(copy,copyLp);

        change=new Button(this);change.setText(tr("↻  Email ပြောင်းမယ်","↻  Change email"));change.setTextSize(16);change.setTextColor(Color.rgb(90,95,104));change.setBackgroundColor(Color.TRANSPARENT);LinearLayout.LayoutParams changeLp=lp(-1,dp(62));changeLp.setMargins(0,dp(18),0,dp(8));root.addView(change,changeLp);

        LinearLayout inboxCard=new LinearLayout(this);inboxCard.setOrientation(LinearLayout.VERTICAL);inboxCard.setPadding(dp(16),dp(15),dp(16),dp(16));inboxCard.setBackground(outlined(WHITE,22));root.addView(inboxCard,lp(-1,-2));
        LinearLayout inboxHead=new LinearLayout(this);inboxHead.setGravity(Gravity.CENTER_VERTICAL);TextView inboxTitle=text("Inbox",20,INK);inboxTitle.setTypeface(Typeface.DEFAULT,Typeface.BOLD);inboxHead.addView(inboxTitle,new LinearLayout.LayoutParams(0,-2,1));count=text("0",13,GREEN);count.setGravity(Gravity.CENTER);count.setBackground(shape(Color.rgb(229,251,244),12));inboxHead.addView(count,lp(dp(36),dp(32)));refresh=new Button(this);refresh.setText("↻");refresh.setTextSize(18);refresh.setTextColor(GREEN);refresh.setEnabled(false);refresh.setBackgroundColor(Color.TRANSPARENT);inboxHead.addView(refresh,lp(dp(48),dp(42)));inboxCard.addView(inboxHead);
        inbox=new LinearLayout(this);inbox.setOrientation(LinearLayout.VERTICAL);inboxCard.addView(inbox,lp(-1,-2));showEmpty();

        Button sponsored=new Button(this);sponsored.setText(tr("ကြော်ငြာကြည့်ရန်  ↗","Sponsored offer  ↗"));sponsored.setTextColor(Color.WHITE);sponsored.setTextSize(14);sponsored.setTypeface(Typeface.DEFAULT,Typeface.BOLD);sponsored.setBackground(shape(Color.rgb(35,39,48),12));LinearLayout.LayoutParams adLp=lp(-1,dp(48));adLp.topMargin=dp(18);root.addView(sponsored,adLp);
        TextView nav=text("✉  Email        ▣  Inbox        ★  More",14,INK);nav.setGravity(Gravity.CENTER);nav.setTypeface(Typeface.DEFAULT,Typeface.BOLD);nav.setBackground(shape(WHITE,28));LinearLayout.LayoutParams navLp=lp(-1,dp(62));navLp.topMargin=dp(18);root.addView(nav,navLp);

        copy.setOnClickListener(v->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Temp email",email.getText()));Toast.makeText(this,tr("ကူးယူပြီးပါပြီ","Email copied"),Toast.LENGTH_SHORT).show();});
        change.setOnClickListener(v->createMailbox());refresh.setOnClickListener(v->loadMessages());
        sponsored.setOnClickListener(v->openSmartlink());
        setContentView(scroll);
        ui.postDelayed(this::offerAutoSmartlink,1200);
    }

    private void offerAutoSmartlink(){android.content.SharedPreferences prefs=getSharedPreferences("settings",MODE_PRIVATE);if(!prefs.contains("auto_smartlink")){new AlertDialog.Builder(this).setTitle(tr("ကြော်ငြာ အလိုအလျောက်ဖွင့်မလား?","Open sponsored link automatically?")).setMessage(tr("ခွင့်ပြုပါက နောက်တစ်ကြိမ်မှစပြီး App ဖွင့်တိုင်း browser တွင် ကြော်ငြာဖွင့်ပါမယ်။ Menu မှ ပြန်ပိတ်နိုင်ပါတယ်။","If allowed, the sponsored link will open in your browser whenever the app starts. You can disable it from the menu.")).setNegativeButton(tr("မဖွင့်ပါ","No"),(d,w)->prefs.edit().putBoolean("auto_smartlink",false).apply()).setPositiveButton(tr("ခွင့်ပြုမယ်","Allow"),(d,w)->{prefs.edit().putBoolean("auto_smartlink",true).apply();openSmartlink();}).show();}else if(prefs.getBoolean("auto_smartlink",false)){openSmartlink();}}
    private void openSmartlink(){try{startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse(SMARTLINK)));}catch(Exception e){Toast.makeText(this,tr("Link ဖွင့်မရပါ","Could not open link"),Toast.LENGTH_SHORT).show();}}

    private void showEmpty(){inbox.removeAllViews();TextView e=text(tr("စာမဝင်သေးပါ\n၁၀ စက္ကန့်တိုင်း စစ်ဆေးပေးပါမယ်","No messages yet\nChecking every 10 seconds"),14,MUTED);e.setGravity(Gravity.CENTER);e.setPadding(0,dp(28),0,dp(22));inbox.addView(e,lp(-1,-2));}
    private void busy(boolean value,String message){status.setText(message);change.setEnabled(!value);refresh.setEnabled(!value&&!token.isEmpty());}
    private void createMailbox(){ui.removeCallbacks(poll);token="";copy.setEnabled(false);email.setText(tr("ဖန်တီးနေသည်…","Creating…"));busy(true,tr("အီးမေးလ်ဖန်တီးနေသည်…","Creating email…"));io.execute(()->{Exception last=null;for(String base:providers){try{JSONObject domains=get(base+"/domains?page=1","GET",null,null);JSONArray list=domains.optJSONArray("hydra:member");if(list==null||list.length()==0)throw new Exception(tr("Domain မရပါ","No domain available"));String domain=list.getJSONObject(0).getString("domain"),address=random(17)+"@"+domain,password="Tb!"+random(22)+"9";JSONObject body=new JSONObject().put("address",address).put("password",password);get(base+"/accounts","POST",body.toString(),null);JSONObject auth=get(base+"/token","POST",body.toString(),null);provider=base;token=auth.getString("token");ui.post(()->{email.setText(address);copy.setEnabled(true);busy(false,tr("အသုံးပြုနိုင်ပါပြီ","Ready to use"));loadMessages();ui.postDelayed(poll,10000);});return;}catch(Exception e){last=e;}}Exception err=last;ui.post(()->{email.setText(tr("Email မဖန်တီးနိုင်ပါ","Could not create email"));busy(false,tr("ချိတ်ဆက်မှု မအောင်မြင်ပါ","Connection failed"));Toast.makeText(this,err==null?tr("ဝန်ဆောင်မှု မရပါ","Service unavailable"):err.getMessage(),Toast.LENGTH_LONG).show();});});}
    private void loadMessages(){if(token.isEmpty())return;refresh.setEnabled(false);io.execute(()->{try{JSONObject data=get(provider+"/messages?page=1","GET",null,token);JSONArray list=data.optJSONArray("hydra:member");ui.post(()->render(list==null?new JSONArray():list));}catch(Exception e){ui.post(()->Toast.makeText(this,tr("Inbox စစ်ဆေးမရပါ","Could not check inbox"),Toast.LENGTH_SHORT).show());}finally{ui.post(()->refresh.setEnabled(true));}});}
    private void render(JSONArray list){inbox.removeAllViews();count.setText(String.valueOf(list.length()));if(list.length()==0){showEmpty();return;}for(int i=0;i<list.length();i++){JSONObject message=list.optJSONObject(i);if(message==null)continue;String id=message.optString("id"),subject=message.optString("subject","(No subject)"),from=message.optJSONObject("from")==null?"Unknown":message.optJSONObject("from").optString("address","Unknown");TextView row=text("✉  "+from+"\n     "+subject,14,INK);row.setPadding(dp(10),dp(15),dp(10),dp(15));row.setBackground(shape(Color.rgb(247,249,252),12));LinearLayout.LayoutParams rowLp=lp(-1,-2);rowLp.topMargin=dp(8);inbox.addView(row,rowLp);row.setOnClickListener(v->openMessage(id));}}
    private void openMessage(String id){io.execute(()->{try{JSONObject message=get(provider+"/messages/"+URLEncoder.encode(id,"UTF-8"),"GET",null,token);String from=message.optJSONObject("from")==null?"Unknown":message.optJSONObject("from").optString("address"),subject=message.optString("subject","(No subject)"),plain=message.optString("text",tr("စာသားမပါပါ","No text content")),html="";JSONArray parts=message.optJSONArray("html");if(parts!=null&&parts.length()>0)html=parts.optString(0,"");if(html.isEmpty())html=message.optString("html","");String content=html.isEmpty()?linkifyPlainText(plain):html;ui.post(()->showMessage(subject,from,content));}catch(Exception e){ui.post(()->Toast.makeText(this,tr("စာကို ဖွင့်မရပါ","Could not open message"),Toast.LENGTH_SHORT).show());}});}
    private String linkifyPlainText(String plain){java.util.regex.Matcher matcher=android.util.Patterns.WEB_URL.matcher(plain);StringBuilder out=new StringBuilder();int end=0;while(matcher.find()){out.append(android.text.TextUtils.htmlEncode(plain.substring(end,matcher.start())));String label=matcher.group(),href=(label.startsWith("http://")||label.startsWith("https://"))?label:"https://"+label;out.append("<a href='").append(android.text.TextUtils.htmlEncode(href)).append("'>").append(android.text.TextUtils.htmlEncode(label)).append("</a>");end=matcher.end();}out.append(android.text.TextUtils.htmlEncode(plain.substring(end)));return "<div class='plain'>"+out.toString().replace("\n","<br>")+"</div>";}
    private void showMessage(String subject,String from,String content){final Dialog dialog=new Dialog(this);dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(18),dp(18),dp(18),dp(14));page.setBackgroundColor(WHITE);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView subjectView=text(subject,21,INK);subjectView.setTypeface(Typeface.DEFAULT,Typeface.BOLD);titles.addView(subjectView);TextView fromView=text("From: "+from,13,MUTED);titles.addView(fromView);head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));Button close=new Button(this);close.setText("×");close.setTextSize(22);close.setTextColor(INK);close.setBackground(shape(Color.rgb(242,245,248),20));head.addView(close,lp(dp(46),dp(46)));page.addView(head,lp(-1,-2));WebView web=new WebView(this);web.setBackgroundColor(Color.WHITE);web.getSettings().setJavaScriptEnabled(false);web.getSettings().setDomStorageEnabled(false);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView view,String url){openMailLink(url);return true;}@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){openMailLink(request.getUrl().toString());return true;}});String html="<!doctype html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'><style>body{font-family:sans-serif;color:#20242b;padding:14px 2px;line-height:1.6;overflow-wrap:anywhere}img{max-width:100%;height:auto}a{color:#00a975;text-decoration:underline}a[style*='background'],.button{display:inline-block;max-width:100%;box-sizing:border-box}.plain{white-space:normal;font-size:16px}</style></head><body>"+content+"</body></html>";web.loadDataWithBaseURL(null,html,"text/html","UTF-8",null);LinearLayout.LayoutParams webLp=lp(-1,0);webLp.weight=1;webLp.topMargin=dp(10);page.addView(web,webLp);Button done=new Button(this);done.setText(tr("ပိတ်မယ်","Close"));done.setTextColor(Color.WHITE);done.setTypeface(Typeface.DEFAULT,Typeface.BOLD);done.setBackground(shape(GREEN,14));LinearLayout.LayoutParams doneLp=lp(-1,dp(52));doneLp.topMargin=dp(10);page.addView(done,doneLp);dialog.setContentView(page);dialog.setOnDismissListener(d->web.destroy());close.setOnClickListener(v->dialog.dismiss());done.setOnClickListener(v->dialog.dismiss());dialog.show();Window window=dialog.getWindow();if(window!=null){window.setBackgroundDrawable(new android.graphics.drawable.ColorDrawable(WHITE));window.setLayout(WindowManager.LayoutParams.MATCH_PARENT,WindowManager.LayoutParams.MATCH_PARENT);}}
    private void openMailLink(String url){try{android.net.Uri uri=android.net.Uri.parse(url);String scheme=uri.getScheme();if("http".equalsIgnoreCase(scheme)||"https".equalsIgnoreCase(scheme))startActivity(new Intent(Intent.ACTION_VIEW,uri));else Toast.makeText(this,tr("ဒီ Link ကို ဖွင့်မရပါ","This link cannot be opened"),Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,tr("Link ဖွင့်မရပါ","Could not open link"),Toast.LENGTH_SHORT).show();}}
    private JSONObject get(String url,String method,String body,String bearer)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setRequestMethod(method);c.setConnectTimeout(15000);c.setReadTimeout(15000);c.setRequestProperty("Accept","application/ld+json, application/json");c.setRequestProperty("Content-Type","application/json");if(bearer!=null)c.setRequestProperty("Authorization","Bearer "+bearer);if(body!=null){c.setDoOutput(true);try(OutputStream out=c.getOutputStream()){out.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code>=400?c.getErrorStream():c.getInputStream();StringBuilder text=new StringBuilder();if(in!=null)try(BufferedReader reader=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String line;while((line=reader.readLine())!=null)text.append(line);}if(code>=400)throw new Exception("Server error "+code);return new JSONObject(text.toString());}
    private String random(int n){String chars="abcdefghjkmnpqrstuvwxyz23456789";StringBuilder value=new StringBuilder();Random random=new Random();for(int i=0;i<n;i++)value.append(chars.charAt(random.nextInt(chars.length())));return value.toString();}
}
